### ISSUE TITLE
How/Where to do the calculation of Priority

### ISSUE THREAD

**Issue by mbernier** [sendgrid/dx-automator#10]
## Issue Summary

One of the main tenants of this automator is that the items can be prioritized using an objective method and by using text or external data to modify the RICE values. By default, we will implement [Intercom's RICE formula](https://blog.intercom.com/rice-simple-prioritization-for-product-managers/). 

From there, modifications should be able to be made to the overall formula. 

For example:
- the total priority value may get a boost from a due date  (e.g. an item due today should be a higher priority than due in a month)
- It may get a boost from the current item status (Intake items should be high, closed should be negative)

### Option 1
- Modify the items table to have a priority_value field, where the end calculation value is stored for quick indexing and searching of tasks
- Modify the items table to have a blob field calls item_data - which would take a JSON array of the parameters and their values for this specific item
- Create a formula setting and an endpoint or function that will calculate the priority_value by replacing the parameters with the values and calculating the result

### Option 2
- Modify the items table to have a priority_value field, where the end calculation value is stored for quick indexing and searching of tasks
- Store the parameters and values in one of the tables as individual rows or columns. 

### Suggestions?
We are open to suggestions. If we get to this task without any suggestions, we may just pick one and hope for the best.

**Comment by thinkingserious** [comment]
+1 for Option 1

I feel that option provides a good mix of constraint vs. flexibility.

**Comment by thinkingserious** [comment]
Done by https://github.com/sendgrid/dx-automator/pull/75
