### ISSUE TITLE
[Plugin - GitHub] - Add GET /members

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/dx-automator#15]
#### Issue Summary

Add a `/members` endpoint [here](https://github.com/sendgrid/dx-automator/blob/develop/plugins/github/project/api/views.py), which would return a list of all members in the organization on a GET.

Please add tests [here](https://github.com/sendgrid/dx-automator/blob/develop/plugins/github/project/tests/test_github.py).

#### Sample Code

```python
members = []
org = self.github.organization(current_app.config['GITHUB_ORG'])
for member in org.iter_members():
    members.append(member.login)
members = jsonify(members)
```

**Comment by af4ro** [comment]
Resolved by #22
