### ISSUE TITLE
Run our *.md documents in this repo through the Grammer.ly service and update

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/dx-automator#31]
#### Issue Summary

We would like to get our English polished up throughout the repo.

#### Aceptance Criteria

* Every .md file in this repo has been run through the Grammer.ly service and updated accordingly

**Comment by ssiddhantsharma** [comment]
@thinkingserious Got it! I have a python script to automate Grammer.ly process!
I am up for this.

**Comment by thinkingserious** [comment]
Thank you @ssiddhantsharma, it's all yours!

**Comment by ssiddhantsharma** [comment]
@thinkingserious I guess you guys need more reviewers for the PR's.
