### ISSUE TITLE
Auto-generate the CHANGELOG.md file upon release

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/dx-automator#35]
#### Issue Summary

For every release, we currently hand craft a CHANGELOG.md update, now we would like to automate this process. Please see the existing CHANGELOG.md for formatting structure.

#### Acceptance Criteria

* A script, which when run, creates a CHANGELOG.md update based on any merged PRs since the last release.

**Comment by harshil1712** [comment]
I would like to try this one

**Comment by thinkingserious** [comment]
Hello @harshil1712,

Are you still interested in working on this one?

With Best Regards,

Elmer
