### ISSUE TITLE
Auto-generate the release notes upon release

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/dx-automator#40]
#### Issue Summary

For every release, we hand craft the release notes on GitHub, now we would like to automate this process. Please see the existing [release notes](https://github.com/sendgrid/dx-automator/releases) for an example. The contents of the release notes are generated from the CHANGELOG.md file. [Here](https://developer.github.com/v3/repos/releases/#create-a-release) is the documentation for updating the release notes via the GitHub API. 

#### Acceptance Criteria
 

* A script, which when run, creates a release note update based on the last deployed release

**Comment by ThirumlaDevi** [comment]
@thinkingserious What I could gather is that we'll have to introduce the changelog.md file (as I couldn't find one in the exiting codebase) and write a github action to automate the release when PR is merged to master. Could you please confirm if this is what you are expecting ? TIA.
