### ISSUE TITLE
Dockerize each example

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/dx-automator#62]
#### Issue Summary

We have demonstration code in the [examples directory](https://github.com/sendgrid/dx-automator/tree/development/examples). We have have had some Python versioning issues, so we want to Dockerize each example (each example can be in it's own folder).

#### Acceptance Criteria

1. Each example is in it's own folder and Dockerized
2. There is a README that explains how to run the example and shut down and clean up the container and image

**Comment by saisiddhant12** [comment]
@thinkingserious 
can I take this up ?

**Comment by childish-sambino** [comment]
I don't think we're needing this given the current state/use of this repo.
