### ISSUE TITLE
Add ability to assign a user to a task

### ISSUE THREAD

**Issue by mbernier** [sendgrid/dx-automator#8]
#### Prerequisites! 
#7 must be completed before this can be done! 

#### Issue Summary

This will require an update on tasks for implementing the user id into the tasks table.

#### Steps to Reproduce

1. Implement [flask Migrate](https://testdriven.io/part-three-flask-migrate) for allowing database migrations (follow the steps at the link, please!)
2. Create the update to the items table, allowing for a foreign key to the Users table (see tasks/statuses for how this can be done) - this field should be null by default on the items table
3. Migrate the database locally
4. Update all /items endpoints to allow for user_id
5. Update tests of items endpoints to allow for user_id
6. Add a test specifically for setting and validating a user_id on an item
7. Add a test specifically for removing and validating removal of user_id on an item
8. Add a test with a user_id that doesn't exist (-99 maybe?) 

When this is done, you should be able to do all item activities with or without a user_id assigned.

**Comment by themousepotato** [comment]
Hey @thinkingserious ! Seems like the link that you've given doesn't exist.
